{
  image_path: image_path, 
  pin_memory: False,

  draft_stage: {
    gf_dim: 64,
    df_dim: 64,
    ch_dim: 3,

    epoch: 18,
    batch_size: 8,
    
    lr: 0.0001,
    beta1: 0.5,
    beta2: 0.9,

    generator_lr_milestones: 8,
    discriminator_lr_milestones: 8,

    w_gan: 0.1,
    w_content: 0.1,
    w_recon: 1.0,
    w_line: 1.0,

    log_interval: 10,
    sampling_interval: 100,
    validation_interval: 1000,
  },

  colorization_stage: {
    draft_model_path: path,
    gf_dim: 64,
    ch_dim: 3,

    epoch: 18,
    batch_size: 8,
    
    lr: 0.0001,
    beta1: 0.5,
    beta2: 0.9,

    generator_lr_milestones: 8,
    discriminator_lr_milestones: 8,

    w_gan: 0.1,
    w_content: 0.1,
    w_recon: 1.0,
    w_line: 1.0,

    log_interval: 10,
    sampling_interval: 100,
    validation_interval: 1000,
  }
}