{
  image_path: , 
  line_path: , 
  pin_memory: True,
  device: cuda:0,
  seed: 2331,
  logdir: ./tensorboard,

  autoencoder: {
    ckpt: ,

    gf_dim: 64,
    ch_dim: 3,

    epoch: 12,
    batch_size: 32,
    
    lr: 0.0001,
    beta1: 0.5,
    beta2: 0.9,

    lr_milestones: 8,

    log_interval: 10,
    sampling_interval: 1000,
    validation_interval: 1000,
  },

  draft: {
    ckpt: ,
    autoencoder_path: ,
    
    in_dim: 5,
    gf_dim: 64,
    df_dim: 64,
    ch_dim: 3,

    epoch: 18,
    batch_size: 64,
    
    lr: 0.0001,
    beta1: 0.5,
    beta2: 0.9,

    lr_milestones: 10,

    w_gan: 0.01,
    w_cont: 0.1,
    w_recon: 1.0,
    w_line: 1.0,

    log_interval: 10,
    sampling_interval: 1000,
    validation_interval: 1000,
  },

  colorization: {
    ckpt: ,
    draft_model_path: ,

    in_dim: 4,
    gf_dim: 64,
    ch_dim: 3,

    epoch: 8,
    batch_size: 8,
    
    lr: 0.0001,
    beta1: 0.5,
    beta2: 0.9,

    lr_milestones: 5,

    log_interval: 10,
    sampling_interval: 100,
    validation_interval: 1000,
  },

 
}